from pathlib import Path
import gzip, json

SRC = Path('ohrana/data.json.gz')
OUT = Path('exact')
OUT.mkdir(exist_ok=True)

with gzip.open(SRC, 'rt', encoding='utf-8') as f:
    data = json.load(f)

if not isinstance(data, list) or len(data) != 465:
    raise SystemExit(f'Expected 465 questions, got {len(data) if isinstance(data, list) else type(data)}')

payload = json.dumps(data, ensure_ascii=False, separators=(',', ':')).replace('</script>', '<\\/script>')

html = r'''<!doctype html><html lang="ru"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><meta name="theme-color" content="#155eef"><meta name="description" content="Быстрый поиск ответов по билетам охраны труда 2024"><link rel="manifest" href="./manifest.webmanifest"><link rel="icon" href="../ohrana/icon-192.png"><title>Охрана труда — точная база 2024</title><style>
:root{--b:#f4f6f8;--c:#fff;--t:#17202a;--m:#667085;--p:#155eef;--g:#067647;--gb:#ecfdf3;--bd:#d0d5dd;--w:#b54708;--wb:#fffaeb}*{box-sizing:border-box}body{margin:0;background:var(--b);color:var(--t);font-family:system-ui,-apple-system,"Segoe UI",Roboto,Arial,sans-serif}.wrap{max-width:900px;margin:auto;padding:14px 12px 60px}.top{position:sticky;top:0;z-index:5;background:rgba(244,246,248,.97);backdrop-filter:blur(9px);padding:10px 0 12px}h1{font-size:23px;margin:0 0 3px}.sub{margin:0 0 12px;color:var(--m);font-size:13px}.search{width:100%;font-size:18px;padding:14px;border:2px solid var(--bd);border-radius:14px;outline:0;background:#fff}.search:focus{border-color:var(--p)}.row{display:flex;gap:8px;align-items:center;flex-wrap:wrap;margin-top:8px}select,button{font:inherit}select{padding:9px 11px;border:1px solid var(--bd);border-radius:11px;background:#fff}.install{display:none;border:0;background:var(--p);color:#fff;border-radius:10px;padding:10px 13px;font-weight:700}.count{font-size:13px;color:var(--m)}.card{background:var(--c);border:1px solid #e4e7ec;border-radius:16px;padding:15px;margin:10px 0;box-shadow:0 2px 10px rgba(16,24,40,.04)}.meta{font-size:13px;color:var(--p);font-weight:800;margin-bottom:7px}.q{font-size:17px;font-weight:700;line-height:1.38}.ans{margin-top:11px;padding:11px 12px;border-radius:12px;background:var(--gb);color:#054f31;font-size:16px;font-weight:800}.ans small{display:block;color:var(--g);font-size:11px;margin-bottom:4px}.warn{margin-top:8px;background:var(--wb);color:var(--w);border-radius:10px;padding:8px 10px;font-size:12px}.empty{text-align:center;color:var(--m);padding:50px 10px}.note{font-size:12px;color:var(--m);padding:18px 2px;line-height:1.45}mark{background:#fff0b3;border-radius:2px}@media(max-width:540px){h1{font-size:21px}.search{font-size:16px}.q{font-size:16px}.ans{font-size:15px}}</style></head><body><main class="wrap"><section class="top"><h1>Охрана труда — быстрый поиск</h1><p class="sub">31 билет · 465 вопросов · вопросы и правильные ответы из файлов «Билеты 2024 Охрана.docx» и «Ответы 2024docx.docx»</p><input id="s" class="search" type="search" placeholder="Введите часть вопроса…" autocomplete="off" autofocus><div class="row"><select id="ticket"><option value="">Все билеты</option></select><span id="count" class="count"></span><button id="install" class="install">Установить приложение</button></div></section><section id="list"></section><div class="note">База собрана по присланным файлам. Правильные варианты берутся из файла ответов; содержание не исправляется по внешним источникам. Несоответствия исходных файлов помечаются предупреждением.</div></main><script>const DATA=__PAYLOAD__;
const $=s=>document.querySelector(s),inp=$('#s'),ticket=$('#ticket'),list=$('#list'),count=$('#count');
const norm=s=>(s||'').toLowerCase().replace(/ё/g,'е').replace(/[^a-zа-я0-9]+/gi,' ').trim();
const stop=new Set(['какие','какой','какая','какое','что','где','когда','кто','как','ли','для','при','из','на','в','по','и','или']);
function terms(){return norm(inp.value).split(/\s+/).filter(x=>x&&(!stop.has(x)||x.length>6))}
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function score(o,ts){if(!ts.length)return 1;const q=norm(o.x),a=norm(o.y),hay=q+' '+a;let z=0;for(const t of ts){if(!hay.includes(t))return-1;z+=q.includes(t)?12:5}const p=norm(inp.value);if(p&&q.includes(p))z+=50;return z}
function hi(s,ts){let out=esc(s);for(const t of [...new Set(ts)].sort((a,b)=>b.length-a.length)){if(t.length<2)continue;const x=t.replace(/[.*+?^${}()|[\]\\]/g,'\\$&');out=out.replace(new RegExp('('+x+')','gi'),'<mark>$1</mark>')}return out}
function render(){const ts=terms(),tv=ticket.value;let a=DATA.filter(o=>!tv||String(o.t)===tv);if(ts.length)a=a.map(o=>[o,score(o,ts)]).filter(v=>v[1]>=0).sort((x,y)=>y[1]-x[1]).map(v=>v[0]);else a=a.slice(0,40);count.textContent=ts.length||tv?'Найдено: '+a.length:'Всего: '+DATA.length+' вопросов';if(!a.length){list.innerHTML='<div class="empty">Ничего не найдено. Попробуйте 1–3 ключевых слова.</div>';return}list.innerHTML=a.slice(0,80).map(o=>'<article class="card"><div class="meta">Билет '+o.t+' · вопрос '+o.q+'</div><div class="q">'+hi(o.x,ts)+'</div><div class="ans"><small>ПРАВИЛЬНЫЙ ОТВЕТ: '+o.a+'</small>'+hi(o.y||('В ключе указан вариант №'+o.a+', но текста этого варианта в билете нет.'),ts)+'</div>'+(o.w?'<div class="warn">⚠ '+esc(o.w)+'</div>':'')+'</article>').join('')}
for(let i=1;i<=31;i++)ticket.insertAdjacentHTML('beforeend','<option value="'+i+'">Билет '+i+'</option>');let tm;inp.addEventListener('input',()=>{clearTimeout(tm);tm=setTimeout(render,60)});ticket.addEventListener('change',render);render();
if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js');let dp=null;window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();dp=e;$('#install').style.display='inline-block'});$('#install').onclick=async()=>{if(!dp)return;dp.prompt();await dp.userChoice;dp=null;$('#install').style.display='none'};</script></body></html>'''.replace('__PAYLOAD__', payload)

(OUT/'index.html').write_text(html, encoding='utf-8')
(OUT/'manifest.webmanifest').write_text(json.dumps({
    'name':'Охрана труда — быстрый поиск','short_name':'Охрана труда','start_url':'./','scope':'./','display':'standalone','background_color':'#f4f6f8','theme_color':'#155eef','lang':'ru','icons':[{'src':'../ohrana/icon-192.png','sizes':'192x192','type':'image/png'},{'src':'../ohrana/icon-512.png','sizes':'512x512','type':'image/png'}]
}, ensure_ascii=False), encoding='utf-8')
(OUT/'sw.js').write_text("const C='exact-v1';const A=['./','./index.html','./manifest.webmanifest','../ohrana/icon-192.png','../ohrana/icon-512.png'];self.addEventListener('install',e=>e.waitUntil(caches.open(C).then(c=>c.addAll(A)).then(()=>self.skipWaiting())));self.addEventListener('activate',e=>e.waitUntil(self.clients.claim()));self.addEventListener('fetch',e=>{if(e.request.method==='GET')e.respondWith(caches.match(e.request).then(r=>r||fetch(e.request)))})", encoding='utf-8')
print('Built', OUT/'index.html', 'questions=', len(data))
