var INITIAL_DATA = window.AUTOPOISK_INITIAL_DATA || [];
var STORAGE_KEY = "avtopoisk_chrome_v12";
var DATA = [];
var plateMap = {'А':'A','В':'B','С':'C','Е':'E','Н':'H','К':'K','М':'M','О':'O','Р':'P','Т':'T','Х':'X','У':'Y'};
function txt(v){return v===null||typeof v==="undefined"?"":String(v)}
function trim(v){return txt(v).replace(/^\s+|\s+$/g,"")}
function normText(v){return trim(v).toLowerCase().replace(/\s+/g," ")}
function normPlate(v){var s=trim(v).toUpperCase(),out="",i,ch;for(i=0;i<s.length;i++){ch=s.charAt(i);out+=plateMap[ch]?plateMap[ch]:ch}return out.replace(/[^A-Z0-9]/g,"")}
function cleanPlate(v){return trim(v).toUpperCase().replace(/\s+/g,"")}
function esc(v){return txt(v).replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;").replace(/'/g,"&#39;")}
function normalize(x){return {model:trim(x.model)||"Не указано",plate:cleanPlate(x.plate),org:trim(x.org),validTo:trim(x.validTo)||"2026-12-31"}}
function canStore(){try{var k="__ap_test__";localStorage.setItem(k,"1");localStorage.removeItem(k);return true}catch(e){return false}}
function persist(){if(!canStore())return false;try{localStorage.setItem(STORAGE_KEY,JSON.stringify(DATA));return true}catch(e){return false}}
function loadData(){var saved=null,parsed,i;if(canStore()){try{saved=localStorage.getItem(STORAGE_KEY)}catch(e){saved=null}}if(saved){try{parsed=JSON.parse(saved);if(parsed&&parsed.length){DATA=[];for(i=0;i<parsed.length;i++)DATA.push(normalize(parsed[i]))}}catch(e){DATA=[]}}if(!DATA.length){DATA=[];for(i=0;i<INITIAL_DATA.length;i++)DATA.push(normalize(INITIAL_DATA[i]));persist()}updateCounts();doSearch()}
function dateObj(s){var p=txt(s).split("-");if(p.length!==3)return null;return new Date(Number(p[0]),Number(p[1])-1,Number(p[2]),12,0,0,0)}
function state(x){if(!x.validTo)return "unknown";var d=dateObj(x.validTo);if(!d)return "unknown";var t=new Date();t=new Date(t.getFullYear(),t.getMonth(),t.getDate(),12,0,0,0);var days=Math.floor((d-t)/86400000);if(days<0)return "expired";if(days<=30)return "soon";return "active"}
function fmtDate(s){if(!s)return "Срок не указан";var p=s.split("-");if(p.length!==3)return s;return p[2]+"."+p[1]+"."+p[0]}
function statusHtml(x){var st=state(x),cl="unknown",label="Срок не указан";if(st==="active"){cl="ok";label="Действует до "+fmtDate(x.validTo)}if(st==="soon"){cl="soon";label="Скоро закончится: "+fmtDate(x.validTo)}if(st==="expired"){cl="expired";label="ПРОПУСК ИСТЁК • действовал до "+fmtDate(x.validTo)}return '<span class="status '+cl+'">'+esc(label)+'</span>'}
function matches(x,q){q=trim(q);if(!q)return false;var qText=normText(q);var text=normText((x.model||"")+" "+(x.plate||"")+" "+(x.org||""));if(qText&&text.indexOf(qText)>=0)return true;var qPlate=normPlate(q);var carPlate=normPlate(x.plate||"");if(qPlate&&carPlate.indexOf(qPlate)>=0)return true;var qDigits=txt(q).replace(/[^0-9]/g,"");var carDigits=txt(x.plate).replace(/[^0-9]/g,"");if(qDigits&&carDigits.indexOf(qDigits)>=0)return true;return false}
function resultCard(x,i){return '<div class="result"><div class="top"><div class="model">'+esc(x.model)+'</div><div class="plate">'+esc(x.plate)+'</div></div><div class="org">'+(x.org?esc(x.org):'<span style="color:#8791a0">Организация не указана</span>')+'</div>'+statusHtml(x)+'<div class="actions"><button class="soft" onclick="editCar('+i+')">✏️ Изменить</button><button class="red" onclick="deleteCar('+i+')">🗑 Удалить</button></div></div>'}
function doSearch(){var q=document.getElementById("q").value;var html="",n=0,i,x;if(!trim(q)){document.getElementById("found").innerHTML="0";document.getElementById("results").innerHTML='<div class="empty">Введите госномер, его часть, марку или организацию. Просроченные автомобили тоже будут найдены и отмечены красным.</div>';return}for(i=0;i<DATA.length;i++){x=DATA[i];if(matches(x,q)){html+=resultCard(x,i);n++}}document.getElementById("found").innerHTML=String(n);document.getElementById("results").innerHTML=html||'<div class="empty">Ничего не найдено.</div>'}
function clearSearch(){document.getElementById("q").value="";doSearch();document.getElementById("q").focus()}
function updateCounts(){var a=0,s=0,e=0,i,st;for(i=0;i<DATA.length;i++){st=state(DATA[i]);if(st==="active")a++;else if(st==="soon")s++;else if(st==="expired")e++}document.getElementById("total").innerHTML=String(DATA.length);document.getElementById("cntActive").innerHTML=String(a);document.getElementById("cntSoon").innerHTML=String(s);document.getElementById("cntExpired").innerHTML=String(e)}
function showSec(n){var names=["Search","Add","Base"],i;for(i=0;i<names.length;i++){document.getElementById("sec"+names[i]).className="section"+(names[i]===n?" active":"");document.getElementById("nav"+names[i]).className=(names[i]===n?"on":"")}if(n==="Base")renderBase();window.scrollTo(0,0)}
function showMsg(text,good){var e=document.getElementById("formMsg");e.className="msg show";e.style.background=good?"#e8f5ee":"#fdecea";e.style.color=good?"#12633f":"#9b251b";e.innerHTML=esc(text);setTimeout(function(){e.className="msg"},2200)}
function saveCar(){var model=trim(document.getElementById("model").value)||"Не указано";var plate=cleanPlate(document.getElementById("plate").value);var org=trim(document.getElementById("org").value);var validTo=trim(document.getElementById("validTo").value);var raw=document.getElementById("editIndex").value;var idx=raw===""?-1:Number(raw),i,dup=-1;if(!plate){showMsg("Введите госномер.",false);return}for(i=0;i<DATA.length;i++){if(i!==idx&&normPlate(DATA[i].plate)===normPlate(plate)){dup=i;break}}if(dup>=0&&!confirm("Такой госномер уже есть. Заменить существующую запись?"))return;if(dup>=0){DATA[dup]={model:model,plate:plate,org:org,validTo:validTo};if(idx>=0&&idx!==dup)DATA.splice(idx,1)}else if(idx>=0){DATA[idx]={model:model,plate:plate,org:org,validTo:validTo}}else{DATA.push({model:model,plate:plate,org:org,validTo:validTo})}persist();updateCounts();cancelEdit();showMsg("Автомобиль сохранён.",true)}
function editCar(i){var x=DATA[i];if(!x)return;document.getElementById("editIndex").value=String(i);document.getElementById("model").value=x.model;document.getElementById("plate").value=x.plate;document.getElementById("org").value=x.org;document.getElementById("validTo").value=x.validTo||"";document.getElementById("formTitle").innerHTML="Изменить автомобиль";document.getElementById("cancelBtn").style.display="block";showSec("Add")}
function cancelEdit(){document.getElementById("editIndex").value="";document.getElementById("model").value="";document.getElementById("plate").value="";document.getElementById("org").value="";document.getElementById("validTo").value="2026-12-31";document.getElementById("formTitle").innerHTML="Добавить автомобиль";document.getElementById("cancelBtn").style.display="none"}
function deleteCar(i){if(!DATA[i])return;if(confirm("Удалить "+DATA[i].plate+"?")){DATA.splice(i,1);persist();updateCounts();doSearch();renderBase()}}
function renderBase(){var f=document.getElementById("baseFilter").value,html="",i,x,st,n=0;for(i=0;i<DATA.length;i++){x=DATA[i];st=state(x);if(f!=="all"&&st!==f)continue;html+='<div class="baseitem"><div class="top"><div class="model">'+esc(x.model)+'</div><div class="plate">'+esc(x.plate)+'</div></div><div class="org">'+esc(x.org||"Организация не указана")+'</div>'+statusHtml(x)+'<div class="actions"><button class="soft" onclick="editCar('+i+')">Изменить</button></div></div>';n++}document.getElementById("baseList").innerHTML=html||'<div class="empty">Нет записей.</div>';updateCounts()}
function downloadBlob(blob,name){var a=document.createElement("a"),u=URL.createObjectURL(blob);a.href=u;a.download=name;document.body.appendChild(a);a.click();setTimeout(function(){URL.revokeObjectURL(u);document.body.removeChild(a)},1000)}
function exportBackup(){var obj={version:12,exported:new Date().toISOString(),cars:DATA};downloadBlob(new Blob([JSON.stringify(obj,null,2)],{type:"application/json;charset=utf-8"}),"AutoPoisk_backup.json")}
function importBackup(file){if(!file)return;var r=new FileReader();r.onload=function(){try{var obj=JSON.parse(r.result),arr=obj.cars||obj,i,newData=[];if(!arr||typeof arr.length==="undefined")throw new Error("format");if(!confirm("Заменить текущую базу на резервную копию ("+arr.length+" записей)?"))return;for(i=0;i<arr.length;i++)newData.push(normalize(arr[i]));DATA=newData;persist();updateCounts();renderBase();doSearch();alert("База восстановлена.")}catch(e){alert("Не удалось прочитать резервную копию.")}};r.readAsText(file,"utf-8");document.getElementById("backupFile").value=""}
let UPDATE_PREVIEW = null;
function normalizeImportDate(v){const s=String(v||'').trim();if(!s)return '';if(/^\d{4}-\d{2}-\d{2}$/.test(s))return s;const m=s.match(/^(\d{1,2})[.\-/](\d{1,2})[.\-/](\d{4})$/);if(m)return m[3]+'-'+String(m[2]).padStart(2,'0')+'-'+String(m[1]).padStart(2,'0');return ''}
function parseUpdateText(text){const source=String(text||'').trim();if(!source)throw new Error('Пакет обновления пуст.');let rows=[],defaultValidTo='';if(source[0]==='{'||source[0]==='['){const obj=JSON.parse(source);if(Array.isArray(obj)){rows=obj}else{rows=Array.isArray(obj.cars)?obj.cars:[];defaultValidTo=normalizeImportDate(obj.defaultValidTo||obj.validTo||'')}}else{const lines=source.split(/\r?\n/).map(x=>x.trim()).filter(Boolean);if(!lines.length)throw new Error('Нет строк для импорта.');const delim=lines[0].indexOf('\t')>=0?'\t':';';rows=lines.map(line=>{const p=line.split(delim);return {model:p[0]||'',plate:p[1]||'',org:p[2]||'',validTo:p[3]||''}});const h=String((rows[0].model||'')+' '+(rows[0].plate||'')+' '+(rows[0].org||'')).toLowerCase();if(h.indexOf('гос')>=0||h.indexOf('номер')>=0||h.indexOf('марка')>=0)rows.shift()}const seen=new Set();const cars=[];let invalid=0,duplicates=0;rows.forEach(r=>{const model=String(r.model??r.brand??r.mark??r['Марка / модель']??r['Марка']??'').trim();const plate=cleanPlate(r.plate??r.number??r.regNumber??r['Гос. номер']??r['Госномер']??'');const org=String(r.org??r.organization??r.company??r['Организация']??'').trim();let validTo=normalizeImportDate(r.validTo??r.valid_to??r.date??r['Пропуск действует до']??r['Действует до']??'');if(!validTo)validTo=defaultValidTo;const key=normPlate(plate);if(!key){invalid++;return}if(seen.has(key)){duplicates++;return}seen.add(key);cars.push({model,plate,org,validTo})});if(!cars.length)throw new Error('В пакете нет корректных госномеров.');return {cars,invalid,duplicates}}
function previewUpdate(){try{const parsed=parseUpdateText(document.getElementById('updateText').value);const existing=new Set(DATA.map(x=>normPlate(x.plate)));let newCount=0,existingCount=0;parsed.cars.forEach(x=>existing.has(normPlate(x.plate))?existingCount++:newCount++);UPDATE_PREVIEW=parsed;const box=document.getElementById('updateSummary');box.className='msg ok';box.innerHTML='<b>Пакет проверен.</b><br>Новых автомобилей: <b>'+newCount+'</b><br>Уже есть в базе: <b>'+existingCount+'</b><br>Дубликатов внутри пакета: <b>'+parsed.duplicates+'</b><br>Некорректных строк: <b>'+parsed.invalid+'</b>'}catch(e){UPDATE_PREVIEW=null;const box=document.getElementById('updateSummary');box.className='msg err';box.textContent='Ошибка: '+(e.message||e)}}
function applyUpdate(){try{const parsed=UPDATE_PREVIEW||parseUpdateText(document.getElementById('updateText').value);const mode=document.getElementById('updateMode').value;const index=new Map();DATA.forEach((x,i)=>index.set(normPlate(x.plate),i));let added=0,updated=0,skipped=0;parsed.cars.forEach(incoming=>{const key=normPlate(incoming.plate);const idx=index.has(key)?index.get(key):-1;if(idx<0){DATA.push(normalize({model:incoming.model||'Не указано',plate:incoming.plate,org:incoming.org,validTo:incoming.validTo}));index.set(key,DATA.length-1);added++;return}if(mode==='add'){skipped++;return}const old=DATA[idx];const next={model:incoming.model?incoming.model:old.model,plate:old.plate||incoming.plate,org:incoming.org?incoming.org:old.org,validTo:incoming.validTo?incoming.validTo:old.validTo};const changed=next.model!==old.model||next.org!==old.org||next.validTo!==old.validTo;DATA[idx]=normalize(next);changed?updated++:skipped++});persist();updateCounts();renderBase();doSearch();const box=document.getElementById('updateSummary');box.className='msg ok';box.innerHTML='<b>Обновление применено.</b><br>Добавлено: <b>'+added+'</b><br>Обновлено: <b>'+updated+'</b><br>Без изменений / пропущено: <b>'+skipped+'</b><br>Всего в базе: <b>'+DATA.length+'</b>';UPDATE_PREVIEW=null}catch(e){const box=document.getElementById('updateSummary');box.className='msg err';box.textContent='Ошибка: '+(e.message||e)}}
function readUpdateFile(file){if(!file)return;const reader=new FileReader();reader.onload=()=>{document.getElementById('updateText').value=String(reader.result||'');UPDATE_PREVIEW=null;previewUpdate()};reader.onerror=()=>{const box=document.getElementById('updateSummary');box.className='msg err';box.textContent='Не удалось прочитать файл.'};reader.readAsText(file,'utf-8')}
function clearUpdate(){document.getElementById('updateText').value='';const f=document.getElementById('updateFile');if(f)f.value='';const box=document.getElementById('updateSummary');box.className='msg';box.textContent='';UPDATE_PREVIEW=null}
(function setupVoiceSearch(){var btn=document.getElementById("voiceBtn"),hint=document.getElementById("voiceHint"),input=document.getElementById("q");var SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!btn||!hint||!input)return;if(!SR){btn.onclick=function(){hint.innerHTML="Голосовой поиск не поддерживается этим браузером. Используйте ручной ввод."};return}var rec=new SR(),listening=false,finalText="";rec.lang="ru-RU";rec.interimResults=true;rec.continuous=false;rec.maxAlternatives=1;rec.onstart=function(){listening=true;finalText="";btn.className="micbtn listening";hint.innerHTML="Слушаю…"};rec.onresult=function(e){var interim="",i,t;for(i=e.resultIndex;i<e.results.length;i++){t=e.results[i][0].transcript;if(e.results[i].isFinal)finalText+=t+" ";else interim+=t}input.value=trim(finalText+interim)};rec.onerror=function(e){if(e.error==="not-allowed"||e.error==="service-not-allowed")hint.innerHTML="Нет доступа к микрофону. Разрешите микрофон для этого сайта.";else if(e.error==="no-speech")hint.innerHTML="Речь не распознана. Нажмите микрофон и повторите.";else hint.innerHTML="Не удалось выполнить голосовой поиск."};rec.onend=function(){listening=false;btn.className="micbtn";if(input.value){doSearch();if(hint.innerHTML==="Слушаю…")hint.innerHTML=""}};btn.onclick=function(){try{if(listening)rec.stop();else rec.start()}catch(e){}}})();
document.getElementById("q").onkeyup=function(){doSearch()};loadData();if("serviceWorker" in navigator){window.addEventListener("load",function(){navigator.serviceWorker.register("./sw.js").catch(function(){})})}