const $=s=>document.querySelector(s),inp=$('#s'),ticket=$('#ticket'),list=$('#list'),count=$('#count'),voice=$('#voice'),hint=$('#voicehint');
const norm=s=>(s||'').toLowerCase().replace(/ё/g,'е').replace(/[^a-zа-я0-9]+/gi,' ').trim();
const GENERIC=new Set(('какие какой какая какое что где когда кто как ли для при из на в во по и или а к ко от до с со у о об про за над под между должен должна должно должны нужно необходимо следует рекомендуется рекомендовано рекомендованы рекомендовать принять придать делать сделать называется является относятся относится требуется разрешается допускается можно нельзя имеется имеет иметь будет быть выбрать выберите укажите указать определите определить перечисленных перечисленное перечисленные следующих следующего ниже верно правильно').split(' '));
const words=s=>norm(s).split(/\s+/).filter(Boolean);
function meaningful(q){const all=words(q).filter(x=>x.length>1),m=all.filter(x=>!GENERIC.has(x));return m.length?m:all}
function pref(w){return w.length<=5?w:w.slice(0,5)}
function termHit(t,arr){if(arr.includes(t))return 3;const p=pref(t);if(p.length>=4&&arr.some(w=>w.length>=4&&pref(w)===p))return 2;return 0}
function normalizeRecord(o){const a=o.a??o.answer??o.correct??o.correctAnswer;let y=o.y??o.correctText??o.answerText??o.correct_answer_text??'';if(!y&&Array.isArray(o.options)&&a!=null){const n=Number(a);if(Number.isFinite(n)&&n>=1)y=o.options[n-1]||''}return{t:o.t??o.ticket??o.bilet??o.ticketNumber,q:o.q??o.question??o.n??o.questionNumber,x:o.x??o.text??o.questionText??'',a,y,w:o.w??o.warning??''}}
const DATA=(window.DATA||[]).map(normalizeRecord);
const IDX=DATA.map(o=>({o,qw:words(o.x),aw:words(o.y),qn:norm(o.x),an:norm(o.y)}));
function score(ix,ts,phrase,allTs){if(!ts.length)return 1;let matched=0,z=0;for(const t of ts){let h=0;if(ix.qn.includes(t)){h=4;z+=28}else{h=termHit(t,ix.qw);if(h)z+=h===3?22:15}if(!h){if(ix.an.includes(t)){h=3;z+=8}else{const ah=termHit(t,ix.aw);if(ah){h=ah;z+=5}}}if(h)matched++}const need=ts.length<=2?ts.length:Math.ceil(ts.length*.6);if(matched<need)return-1;if(phrase&&ix.qn.includes(phrase))z+=90;for(const t of allTs||[]){if(!ts.includes(t)&&t.length>3&&ix.qn.includes(t))z+=4}z+=matched*4;return z}
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function hi(s,ts){let out=esc(s);for(const t of [...new Set(ts)].sort((a,b)=>b.length-a.length)){if(t.length<3)continue;const x=t.replace(/[.*+?^${}()|[\]\\]/g,'\\$&');out=out.replace(new RegExp('('+x+')','gi'),'<mark>$1</mark>')}return out}
function searchNow(){const allTs=words(inp.value),ts=meaningful(inp.value),phrase=norm(inp.value),tv=ticket.value;let a=IDX.filter(ix=>!tv||String(ix.o.t)===tv);if(ts.length)a=a.map(ix=>[ix,score(ix,ts,phrase,allTs)]).filter(v=>v[1]>=0).sort((x,y)=>y[1]-x[1]).map(v=>v[0].o);else a=a.slice(0,40);count.textContent=ts.length||tv?'Найдено: '+a.length:'Всего: '+DATA.length+' вопросов';if(!a.length){list.innerHTML='<div class="empty">Ничего не найдено. Можно сказать короче: 1–3 ключевых слова из вопроса.</div>';return}list.innerHTML=a.slice(0,80).map(o=>'<article class="card"><div class="meta">Билет '+esc(o.t??'?')+' · вопрос '+esc(o.q??'?')+'</div><div class="q">'+hi(o.x,ts)+'</div><div class="ans"><small>ПРАВИЛЬНЫЙ ОТВЕТ: '+esc(o.a??'?')+'</small>'+hi(o.y||('В ключе указан вариант №'+(o.a??'?')+', но текста этого варианта в билете нет.'),ts)+'</div>'+(o.w?'<div class="warn">⚠ '+esc(o.w)+'</div>':'')+'</article>').join('')}
for(let i=1;i<=31;i++)ticket.insertAdjacentHTML('beforeend','<option value="'+i+'">Билет '+i+'</option>');let tm;inp.addEventListener('input',()=>{clearTimeout(tm);tm=setTimeout(searchNow,40)});ticket.addEventListener('change',searchNow);searchNow();
(()=>{const SR=window.SpeechRecognition||window.webkitSpeechRecognition;let rec;if(!SR){voice.addEventListener('click',()=>hint.textContent='Голосовой ввод не поддерживается этим браузером. Лучше открыть страницу в Chrome.');return}rec=new SR();rec.lang='ru-RU';rec.interimResults=false;rec.continuous=false;rec.maxAlternatives=1;rec.onstart=()=>{voice.classList.add('listening');voice.textContent='●';hint.textContent='Говорите…'};rec.onresult=e=>{const t=(e.results&&e.results[0]&&e.results[0][0]&&e.results[0][0].transcript||'').trim();if(!t)return;inp.value=t;searchNow();inp.focus();hint.textContent='Распознано: «'+t+'»'};rec.onerror=e=>{let m='Не удалось распознать речь.';if(e.error==='not-allowed'||e.error==='service-not-allowed')m='Разрешите браузеру доступ к микрофону.';else if(e.error==='no-speech')m='Речь не услышана. Нажмите микрофон и попробуйте ещё раз.';else if(e.error==='audio-capture')m='Микрофон недоступен.';hint.textContent=m};rec.onend=()=>{voice.classList.remove('listening');voice.textContent='🎤'};voice.addEventListener('click',()=>{try{rec.start()}catch(_){}})})();